<html>
<head>
	<script type="text/javascript" src="js/jquery-1.7.1.min.js"></script>
	<!--[if IE]><script type="text/javascript" src="js/excanvas.js"></script><![endif]-->
	<script type="text/javascript" src="js/coolclock.js"></script>
	<script type="text/javascript" src="js/moreskins.js"></script>
	<script type="text/javascript">
	$(document).ready(function() {
		
		$("#zones").change(function(){
			if ($('#time-cont .time').length>0){ $('#time-cont .time').remove();}
			var offset = $(this).val();
			if (offset == '') return;      	 
			$('#_coolclock').attr('class','CoolClock:swissRail:::'+offset);
			CoolClock.findAndCreateClocks();
		});
	});	
	</script>
 
</head>
  <body>
	<select id="zones">
	    <option value="">--Select--</option>
	    <option value='4.5'>Afghanistan</option>
		<option value='1'>Albania</option>
		<option value='1'>Algeria</option>
		<option value='-11'>American Samoa</option>
		<option value='1'>Andorra</option>
		<option value='1'>Angola</option>
		<option value='-4'>Anguilla</option>
		<option value='-2'>Antarctica</option>
		<option value='-4'>Antigua</option>
		<option value='-3'>Argentina</option>
		<option value='-4'>Argentina western prov</option>
		<option value='4'>Armenia</option>
		<option value='-4'>Aruba</option>
		<option value='0'>Ascension</option>
		<option value='9.5'>Australia Northern Territory</option>
		<option value='10.5'>Australia Lord Howe Island</option>
		<option value='10'>Australia New South Wales</option>
		<option value='10'>Australia Queensland</option>
		<option value='10'>Australia Victoria</option>
		<option value='10'>Australia Australian Captial Territory</option>
		<option value='9.5'>Australia South</option>
		<option value='10'>Australia Tasmania</option>
		<option value='8'>Australia Western</option>
		<option value='1'>Austria</option>
		<option value='3'>Azerbajian</option>
		<option value='-1'>Azores</option>
		<option value='-5'>Bahamas</option>
		<option value='3'>Bahrain</option>
		<option value='1'>Balearic Islands</option>
		<option value='6'>Bangladesh</option>
		<option value='-4'>Barbados</option>
		<option value='2'>Belarus</option>
		<option value='1'>Belgium</option>
		<option value='-6'>Belize</option>
		<option value='1'>Benin</option>
		<option value='-4'>Bermuda</option>
		<option value='6'>Bhutan</option>
		<option value='-4'>Bolivia</option>
		<option value='-4'>Bonaire</option>
		<option value='1'>Bosnia Hercegovina</option>
		<option value='2'>Botswana</option>
		<option value='-4'>Brazil Acre</option>
		<option value='-1'>Brazil Atlantic Islands</option>
		<option value='-3'>Brazil East</option>
		<option value='-4'>Brazil West</option>
		<option value='-4'>British Virgin Islands</option>
		<option value='8'>Brunei</option>
		<option value='2'>Bulgaria</option>
		<option value='0'>Burkina Faso</option>
		<option value='2'>Burundi</option>
		<option value='7'>Cambodia</option>
		<option value='1'>Cameroon</option>
		<option value='-6'>Canada Central</option>
		<option value='-5'>Canada Eastern</option>
		<option value='-7'>Canada Mountain</option>
		<option value='-8'>Canada Yukon & Pacific</option>
		<option value='-4'>Canada Atlantic</option>
		<option value='-3.5'>Canada Newfoundland</option>
		<option value='0'>Canary Islands</option>
		<option value='-11'>Canton Enderbury Islands</option>
		<option value='-1'>Cape Verde</option>
		<option value='11'>Caroline Island</option>
		<option value='-5'>Cayman Islands</option>
		<option value='1'>Central African Rep</option>
		<option value='1'>Chad</option>
		<option value='0'>Channel Islands</option>
		<option value='12.75'>Chatham Island</option>
		<option value='-4'>Chile</option>
		<option value='8'>China People's Rep</option>
		<option value='-10'>Christmas Islands</option>
		<option value='-5'>Colombia</option>
		<option value='1'>Congo</option>
		<option value='-10'>Cook Islands</option>
		<option value='-6'>Costa Rica</option>
		<option value='0'>Cote d'Ivoire</option>
		<option value='1'>Croatia</option>
		<option value='-5'>Cuba</option>
		<option value='-4'>Curacao</option>
		<option value='2'>Cyprus</option>
		<option value='1'>Czech Republic</option>
		<option value='1'>Dahomey</option>
		<option value='1'>Denmark</option>
		<option value='3'>Djibouti</option>
		<option value='-4'>Dominica</option>
		<option value='-4'>Dominican Republic</option>
		<option value='-6'>Easter Island</option>
		<option value='-5'>Ecuador</option>
		<option value='2'>Egypt</option>
		<option value='-6'>El Salvador</option>
		<option value='0'>England</option>
		<option value='1'>Equitorial Guinea</option>
		<option value='3'>Eritrea</option>
		<option value='2'>Estonia</option>
		<option value='3'>Ethiopia</option>
		<option value='-4'>Falkland Islands</option>
		<option value='0'>Faroe Island</option>
		<option value='12'>Fiji</option>
		<option value='2'>Finland</option>
		<option value='1'>France</option>
		<option value='-3'>French Guiana</option>
		<option value='-10'>French Polynesia</option>
		<option value='1'>Gabon</option>
		<option value='-5'>Galapagos Islands</option>
		<option value='0'>Gambia</option>
		<option value='-9'>Gambier Island</option>
		<option value='4'>Georgia</option>
		<option value='1'>Germany</option>
		<option value='0'>Ghana</option>
		<option value='1'>Gibraltar</option>
		<option value='2'>Greece</option>
		<option value='-3'>Greenland</option>
		<option value='-4'>Greenland Thule</option>
		<option value='-1'>Greenland Scoresbysun</option>
		<option value='-4'>Grenada</option>
		<option value='-4'>Grenadines</option>
		<option value='-4'>Guadeloupe</option>
		<option value='10'>Guam</option>
		<option value='-6'>Guatemala</option>
		<option value='0'>Guinea</option>
		<option value='0'>Guinea Bissau</option>
		<option value='-3'>Guyana</option>
		<option value='-5'>Haiti</option>
		<option value='-6'>Honduras</option>
		<option value='8'>Hong kong</option>
		<option value='1'>Hungary</option>
		<option value='0'>Iceland</option>
		<option value='5.5'>India</option>
		<option value='8'>Indonesia Central</option>
		<option value='9'>Indonesia East</option>
		<option value='7'>Indonesia West</option>
		<option value='3.5'>Iran</option>
		<option value='3'>Iraq</option>
		<option value='0'>Ireland Republic of</option>
		<option value='2'>Israel</option>
		<option value='1'>Italy</option>
		<option value='-5'>Jamaica</option>
		<option value='9'>Japan</option>
		<option value='-10'>Johnston Island</option>
		<option value='2'>Jordan</option>
		<option value='6'>Kazakhstan</option>
		<option value='3'>Kenya</option>
		<option value='12'>Kiribati</option>
		<option value='9'>Korea Dem Republic of</option>
		<option value='9'>Korea Republic of</option>
		<option value='12'>Kusaie</option>
		<option value='3'>Kuwait</option>
		<option value='-12'>Kwajalein</option>
		<option value='5'>Kyrgyzstan</option>
		<option value='7'>Laos</option>
		<option value='2'>Latvia</option>
		<option value='2'>Lebanon</option>
		<option value='-4'>Leeward Islands</option>
		<option value='2'>Lesotho</option>
		<option value='0'>Liberia</option>
		<option value='2'>Libya</option>
		<option value='2'>Lithuania</option>
		<option value='1'>Luxembourg</option>
		<option value='1'>Macedonia</option>
		<option value='3'>Madagascar</option>
		<option value='0'>Madeira</option>
		<option value='2'>Malawi</option>
		<option value='8'>Malaysia</option>
		<option value='5'>Maldives</option>
		<option value='0'>Mali</option>
		<option value='1'>Mallorca Islands</option>
		<option value='1'>Malta</option>
		<option value='10'>Mariana Island</option>
		<option value='-9.5'>Marquesas Islands</option>
		<option value='12'>Marshall Islands</option>
		<option value='-4'>Martinique</option>
		<option value='0'>Mauritania</option>
		<option value='4'>Mauritius</option>
		<option value='3'>Mayotte</option>
		<option value='1'>Melilla</option>
		<option value='-6'>Mexico</option>
		<option value='-8'>Mexico Baja Calif Norte</option>
		<option value='-7'>Mexico Nayarit</option>
		<option value='-7'>Mexico Sinaloa</option>
		<option value='-7'>Mexico Sonora</option>
		<option value='-11'>Midway Island</option>
		<option value='2'>Moldova</option>
		<option value='2'>Moldovian Rep Pridnestrovye</option>
		<option value='1'>Monaco</option>
		<option value='8'>Mongolia</option>
		<option value='0'>Morocco</option>
		<option value='2'>Mozambique</option>
		<option value='6.5'>Myanmar</option>
		<option value='1'>Namibia</option>
		<option value='12'>Nauru Republic of</option>
		<option value='5.75'>Nepal</option>
		<option value='1'>Netherlands</option>
		<option value='-4'>Netherlands Antilles</option>
		<option value='-4'>Nevis Montserrat</option>
		<option value='11'>New Caledonia</option>
		<option value='11'>New Hebrides</option>
		<option value='12'>New Zealand</option>
		<option value='-6'>Nicaragua</option>
		<option value='1'>Niger</option>
		<option value='1'>Nigeria</option>
		<option value='-11'>Niue Island</option>
		<option value='11.5'>Norfolk Island</option>
		<option value='0'>Northern Ireland</option>
		<option value='10'>Northern Mariana Islands</option>
		<option value='1'>Norway</option>
		<option value='4'>Oman</option>
		<option value='5'>Pakistan</option>
		<option value='9'>Palau</option>
		<option value='-5'>Panama</option>
		<option value='10'>Papua New Guinea</option>
		<option value='-4'>Paraguay</option>
		<option value='-5'>Peru</option>
		<option value='8'>Philippines</option>
		<option value='12'>Pingelap</option>
		<option value='1'>Poland</option>
		<option value='11'>Ponape Island</option>
		<option value='1'>Portugal</option>
		<option value='0'>Principe Island</option>
		<option value='-4'>Puerto Rico</option>
		<option value='3'>Qatar</option>
		<option value='4'>Reunion</option>
		<option value='2'>Romania</option>
		<option value='2'>Russian Federation zone one</option>
		<option value='4'>Russian Federation zone two</option>
		<option value='4'>Russian Federation zone three</option>
		<option value='5'>Russian Federation zone four</option>
		<option value='6'>Russian Federation zone five</option>
		<option value='7'>Russian Federation zone six</option>
		<option value='8'>Russian Federation zone seven</option>
		<option value='9'>Russian Federation zone eight</option>
		<option value='10'>Russian Federation zone nine</option>
		<option value='11'>Russian Federation zone ten</option>
		<option value='12'>Russian Federation zone eleven</option>
		<option value='2'>Rwanda</option>
		<option value='-4'>Saba</option>
		<option value='-11'>Samoa</option>
		<option value='1'>San Marino</option>
		<option value='0'>Sao Tome e Principe</option>
		<option value='3'>Saudi Arabia</option>
		<option value='0'>Scotland</option>
		<option value='0'>Senegal</option>
		<option value='4'>Seychelles</option>
		<option value='0'>Sierra Leone</option>
		<option value='8'>Singapore</option>
		<option value='1'>Slovakia</option>
		<option value='1'>Slovenia</option>
		<option value='-10'>Society Island</option>
		<option value='11'>Solomon Islands</option>
		<option value='3'>Somalia</option>
		<option value='2'>South Africa</option>
		<option value='1'>Spain</option>
		<option value='5.5'>Sri Lanka</option>
		<option value='-4'>St Christopher</option>
		<option value='-4'>St Croix</option>
		<option value='0'>St Helena</option>
		<option value='-4'>St John</option>
		<option value='-4'>St Kitts Nevis</option>
		<option value='-4'>St Lucia</option>
		<option value='-4'>St Maarten</option>
		<option value='-3'>St Pierre & Miquelon</option>
		<option value='-4'>St Thomas</option>
		<option value='-4'>St Vincent</option>
		<option value='2'>Sudan</option>
		<option value='-3'>Suriname</option>
		<option value='2'>Swaziland</option>
		<option value='1'>Sweden</option>
		<option value='1'>Switzerland</option>
		<option value='2'>Syria</option>
		<option value='-10'>Tahiti</option>
		<option value='8'>Taiwan</option>
		<option value='6'>Tajikistan</option>
		<option value='3'>Tanzania</option>
		<option value='7'>Thailand</option>
		<option value='0'>Togo</option>
		<option value='13'>Tonga</option>
		<option value='-4'>Trinidad and Tobago</option>
		<option value='-10'>Tuamotu Island</option>
		<option value='-10'>Tubuai Island</option>
		<option value='1'>Tunisia</option>
		<option value='2'>Turkey</option>
		<option value='5'>Turkmenistan</option>
		<option value='-5'>Turks and Caicos Islands</option>
		<option value='12'>Tuvalu</option>
		<option value='3'>Uganda</option>
		<option value='2'>Ukraine</option>
		<option value='4'>United Arab Emirates</option>
		<option value='0'>United Kingdom</option>
		<option value='-5'>USA Eastern</option>
		<option value='-5'>USA Indiana East</option>
		<option value='-6'>USA Central</option>
		<option value='-7'>USA Arizona</option>
		<option value='-7'>USA Mountain</option>
		<option value='-8'>USA Pacific</option>
		<option value='-9'>USA Alaska</option>
		<option value='-10'>USA Aleutian</option>
		<option value='-10'>USA Hawaii</option>
		<option value='-3'>Uruguay</option>
		<option value='5'>Uzbekistan</option>
		<option value='11'>Vanuatu</option>
		<option value='1'>Vatican City</option>
		<option value='-4'>Venezuela</option>
		<option value='7'>Vietnam</option>
		<option value='-4'>Virgin Islands</option>
		<option value='12'>Wake Island</option>
		<option value='0'>Wales</option>
		<option value='12'>Wallis and Futuna Islands</option>
		<option value='-4'>Windward Islands</option>
		<option value='3'>Yemen</option>
		<option value='1'>Yugoslavia</option>
		<option value='2'>Zaire Kasai</option>
		<option value='1'>Zaire Kinshasa Mbandaka</option>
		<option value='2'>Zaire Haut Zaire</option>
		<option value='2'>Zaire Kivu</option>
		<option value='2'>Zaire Shaba</option>
	</select>
  	<div id="time-cont">
  		<canvas id="_coolclock" width="170" height="170" style="width: 170px; height: 170px;"></canvas>
  	</div>
</body>
</html>